# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Johnny's Personal Wiki
tagline:          ''
description:      ''
url:              http://jwu.github.com

author:
  name:           'Johnny Wu'
  url:            http://github.com/jwu

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/jwu

redcarpet:
  extensions:     [
      "no_intra_emphasis", 
      "fenced_code_blocks", 
      "autolink", 
      "strikethrough", 
      "superscript",
      "tables",
      "with_toc_data",
  ]
